version: '3.8'

services:
  dev:
    image: haskell:latest
    volumes:
      - "stack:/root/.stack"
    
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - "db-data:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


volumes:
  db-data:
  stack:
